"""Professional1 pincode

Revision ID: 420fe10c9ddc
Revises: 87d90420838c
Create Date: 2025-03-28 17:56:11.127311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '420fe10c9ddc'
down_revision = '87d90420838c'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("professional") as batch_op:
        batch_op.add_column(sa.Column('pincode', sa.String(length=10), nullable=True))  # Step 1: Add column as nullable first

    conn = op.get_bind()  # Get database connection
    conn.execute(sa.text("UPDATE professional SET pincode = '000000'"))  # Step 2: Set default value for existing records

    with op.batch_alter_table("professional") as batch_op:
        batch_op.alter_column('pincode', existing_type=sa.String(length=10), nullable=False)  # Step 3: Make column NOT NULL

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional', schema=None) as batch_op:
        batch_op.drop_column('pincode')

    # ### end Alembic commands ###
