"""Added ServingPincode table

Revision ID: 570326eb35da
Revises: 447e07d4fe85
Create Date: 2025-03-28 14:33:01.047851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '570326eb35da'
down_revision = '447e07d4fe85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('serving_pincode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service.service_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('serving_pincode')
    # ### end Alembic commands ###
