"""Professional1

Revision ID: 87d90420838c
Revises: 570326eb35da
Create Date: 2025-03-28 17:41:21.573829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87d90420838c'
down_revision = '570326eb35da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professional',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('contact', sa.String(length=15), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('joined_date', sa.DateTime(), nullable=True),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('availability', sa.Boolean(), nullable=True),
    sa.Column('govt_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service.service_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('govt_id')
    )
    op.create_table('professional_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.Column('doc_link', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['professional_id'], ['professional.pid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('professional_document')
    op.drop_table('professional')
    # ### end Alembic commands ###
